nationalarchives/ds-caselaw-utils

.github/workflows/test.yml
README.md
poetry.lock
pyproject.toml
src/ds_caselaw_utils/data/neutral_citation_regex.yaml
src/ds_caselaw_utils/neutral.py

For being able to edit the Neutral Citation code in one place, we need the data in a language-agnostic format.
JSON is awful because there's no mechanism for raw strings (where `\` is just a `\` and doesn't need escaping as `\\\`. So we use YAML instead. This does require adding a library because it's not a Python built-in.
We might choose to change where the data is stored later, but this is a useful step on the road.
(Bumps version to 0.1.5 pre-emptively)

Use YAML file for configuration

---

src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/data/neutral_citation_regex.yaml
src/ds_caselaw_utils/test_neutral.py

We add `2022 EWHC 4 (KB)` to the neutral citation to URL solver and update the unused list of courts.

The Queen's Bench Division is now King's Bench Division

---

CHANGELOG.md
README.md
pyproject.toml
src/ds_caselaw_utils/__init__.py
src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/test_courts.py
src/ds_caselaw_utils/test_neutral.py

This adds a `courts` object which allows access to metadata about the courts whose judgments we hold, loaded from the `court_names.yml` file in the data folder. This file has been augmented with metadata used elsewhere in the app, with the aim of it being a single source of truth for information about courts used in the app.

Add helpers for accessing court metadata

---

CHANGELOG.md
README.md
pyproject.toml
src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/test_courts.py

This was an oversight on my part when i first wrote the court list class - there's one list in the public UI which still has court names hardcoded, and we want to bring them in from the list here, but we need them to be grouped slightly differently. This adds accessors to allow that!

Release/v0.4.0 - add accessors for all listable courts/tribunals

---

src/ds_caselaw_utils/data/court_names.yaml

See [this trello card](https://trello.com/c/M3dSLGfX/263-change-year-ranges-for-browse-by-court) - Currently if no `end_year` is set for a court in the YAML, the displayed end_year is set to the current calendar year, which is misleading when we haven't yet ingested any judgments in the current year for that court. As a temporary fix, we've given every court a 2022 end date, which can be manually updated as and when we receive 2023 judgments for them. Longer term, this value should probably accessed dynamically from marklogic rather than set in static metadata.

Fix all court end dates to 2022

---

CHANGELOG.md
README.md
pyproject.toml

We broke the release process for 0.4.5.
Fix 0.4.5, update the docs to make it clear which files actually need updating, and fix the broken history links in the changelog.

Fix release 0.4.5 and touch up docs

---

src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/test_courts.py

Raising an exception is the right behaviour here, but the KeyError that is raised currently isn't very informative, and leaks implementation details unncesessarily.

Raise CourtNotFoundException when param or code not found

---

.github/workflows/codeql.yml
.pre-commit-config.yaml
CHANGELOG.md
src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/data/neutral_citation_regex.yaml
src/ds_caselaw_utils/data/schema/courts.schema.json

At the moment we don't systematically validate the courts data; we rely entirely on code reviews to catch mistakes, or hope that a downstream test will surface any issues before they reach production.
This introduces a schema for the `court_names.yml` file which describes valid data, and checks it using pre-commit.
As a bonus, since this repository has quite a bit of data, we now run prettier over that data to make sure formatting is clean and consistent both within the files and with similar data elsewhere in the project.

Add JSON Schema to validate courts data

---

src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/test_courts.py

Minor tweak so instead of `<ds_caselaw_utils.courts.Court object at 0x1039f91d0>` it shows the name of the court.

Courts display their name in repr contexts

---

src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/test_courts.py

Some groups are 'dummy' ones (eg 'supreme court') which only contain a single court, and others should be displayed in the UI as headings (eg 'high court') - this adds a simple property to make this check when rendering the groups in the PUI. Happily 99% of the rest of what we need for the court heirarchy work was already there!

Add helper to CourtGroups to determine if they should be displayed

---

src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/test_courts.py

An earlier oversight - the courts we want to show grouped in the context of the search form are the _selectable_ courts, not the _listable_ ones.

Add 'get_selectable_groups' method

---

src/ds_caselaw_utils/data/court_names.yaml

The Upper Tribunal (Immigation and Asylum Chamber) used to be called the "Asylum and Immigration Tribunal", with a different NCN format (and therefore URL param). This updates the court metadata to treat it the same way as we do with other renamed courts - a single 'select' box for both names which transparently searches both 'courts', and two entries in all lists with the appropriate dates (eg on the about this service page).

update UKAIT metadata in court_names.yml

---

src/ds_caselaw_utils/data/court_names.yaml

A little bit of an oversight in my PR before - we should allow the parameter alias, but not list the two courts seperately in the UI (the same as we do with scco/costs, rather than queens bench / kings bench)

Don't list old asylum and immigration tribunal

---

src/ds_caselaw_utils/data/court_names.yaml

The editor UI (via the api client) relies on this to validate that the inputted court code is correct, so UKAIT needs its own section even though it's not ever displayed in the public UI (selectable and listable are both `false`).

Add a UKAIT court to the yaml file

---

CHANGELOG.md
pyproject.toml
src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/data/schema/courts.schema.json

Should fix https://trello.com/c/FRTNXptE/1629-family-court-filter-displaying-b-when-it-should-not-be
Also updates version number

Fix EWFC (B) appearing in public-ui

---

CHANGELOG.md
src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/data/schema/courts.schema.json
src/ds_caselaw_utils/test_courts.py

The General Regulatory Chamber has a number of _Jurisdictions_ (or 'sub-tribunals' as we sometimes call them). These are different to the separate _Lists_ we see within eg the Chancery Division - _Lists_ are an administrative distinction, decided on by the court themselves, whereas _Jurisdictions_ are a statutory one, decided in law. Neither jurisdiction nor list affects the NCN of the judgment, but they're stored differently in the XML - Lists are represented in the court code in the <uk:court> element, whereas judgments are represented with the <uk:jurisdiction> element in addition to the <uk:court>.
This PR extends the existing court metadata model to include the new Jurisdictions. Courts can contain multiple Jurisdictions with their own code and name, and a Jurisdiction can be looked …

Add Jurisdiction info to Courts

---

CHANGELOG.md
src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/test_courts.py

Fix bug where getting a nonexistent jurisdiction for a court raised an IndexError. Now we ~~default to returning the parent court~~ explicitly return a CourtNotFoundError for unknown jurisdictions.

fix indexError on getting a non-existent jurisdiction

---

.gitignore
.pre-commit-config.yaml
pyproject.toml
setup.cfg
src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/test_courts.py

A series of commits which together make all of FCL's repositories behave more consistently with regard to tooling.
FCL-176

[FCL-176] Tooling configuration audit

---

.github/workflows/publish.yml

in response to the following error in the logs:
You are using `pypa/gh-action-pypi-publish@master`. The `master` branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use `pypa/gh-action-pypi-publish@release/v1`. If you feel adventurous, you may opt to use use `pypa/gh-action-pypi-publish@unstable/v1` instead. A more general recommendation is to pin to exact tags or commit SHAs.
Please also consider migrating your setup to use secretless publishing: https://github.com/marketplace/actions/pypi-publish#trusted-publishing

Pin pypi-publish to v1

---

src/ds_caselaw_utils/data/court_names.yaml

The URL of [2022] UKIPTrib 3 is /2022/ukiptrib/3 . 
The public and editor converters are correct:
public/judgments/converters.py
28:    regex = "ewhc|uksc|ukpc|ewca|ewcop|ewfc|ukut|eat|ukftt|ukait|ukiptrib"
editor/judgments/converters.py
28:    regex = "ewhc|uksc|ukpc|ewca|ewcop|ewfc|ukut|eat|ukftt|ukait|ukiptrib"
Bug in https://national-archives.atlassian.net/jira/software/projects/FCL/boards/136?selectedIssue=FCL-134

[FCL-134] Use ukiptrib as url, not ukipt

---

.github/workflows/publish.yml

Very speculative, I'm afraid, not sure if this'll work. History below.

Modify pypi-publish to match tag

---

src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/data/neutral_citation_regex.yaml
src/ds_caselaw_utils/test_neutral.py

https://dxw.slack.com/archives/C04FQ3GFGUQ/p1725269335416609
> Jim's parser change for crown court (Changing EWCRC to EWCR) is going to go through at midday, is is possible to make the other changes (EUI, regex) to change the crown court code today so that the judgment can be published?

EWCR not EWCRC

---

src/ds_caselaw_utils/courts.py

We are now explicit about the shape of the dicts we use to retrieve courts by code/param, which in turn forces us to be explicit about how we set them and interact with them.

fix(courts): add additional type statements for stricter behaviour of courts repository

---

src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/data/schema/courts.schema.json
src/ds_caselaw_utils/test_courts.py
src/ds_caselaw_utils/types/__init__.py
src/ds_caselaw_utils/types/courts_schema_autogen.py

`Court.ncn` is now `Court.ncn_pattern`, and is explicitly typed as being a subtype of a regular expression pattern. This is because it looked very similar to representing a Neutral Citation (ie the NCN of an individual judgment), and not (as it actually case) representing the pattern which valid NCNs for that court must match.
BREAKING CHANGE: `Court.ncn` is now `Court.ncn_pattern`, and now returns a `NeutralCitationPattern` which is a subtype of `re.Pattern[str]`.

Fix unintuitive behaviour of Court.ncn

---

CHANGELOG.md
pyproject.toml

- `Court.ncn` is now `Court.ncn_pattern`, and now returns a `NeutralCitationPattern` which is a subtype of `re.Pattern[str]`.
- Existing calls to `neutral_url()` will need to be made type-aware in all downstream projects where typechecking is used.
- **Court**: make it clearer what Court.ncn actually means
- **types**: add new types for NCN-related strings
- **courts**: add additional type statements for stricter behaviour of courts repository
- **types**: move autogen court types to new types submodule

bump: version 1.7.0 → 2.0.0

---

src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/test_courts.py

During debugging, it was annoying that I couldn't see what CourtRepos were.

Add repr to multicourt objects

---

CHANGELOG.md
pyproject.toml

- **Court**: add support text for old documents as HTML
- **Court**: add court descriptions as HTML
- **deps**: update dependency ruamel.yaml to v0.18.10
- **deps**: update dependency ruamel.yaml to v0.18.8
- **deps**: update dependency ruamel.yaml to v0.18.7
- **Court**: make Markdown loading/rendering reusable

bump: version 2.0.1 → 2.1.0

---

src/ds_caselaw_utils/data/markdown/historic_docs/ukiptrib.md

The earliest date for historic documents was incorrectly listed as 2020. The year has been corrected to 2003.

Update ukiptrib.md date 2020 to 2003

---

CHANGELOG.md
courts.md
src/ds_caselaw_utils/data/court_names.yaml
src/ds_caselaw_utils/data/schema/courts.schema.json
src/ds_caselaw_utils/types/courts_schema_autogen.py

This introduces a new constraint on the schema, where `param` must be present if either `listable` or `selectable` are true.
FCL-800

[FCL-800] Make court params obligatory where courts are selectable or listable

---

CHANGELOG.md
pyproject.toml

This includes the changes we should have included in v2.4.2, namely a fix for mercantile court having an incorrect NCN pattern.

Release v2.4.3

---

courts.md
src/ds_caselaw_utils/data/court_names.yaml

Replace the `&` with `and` in the High Court (England and Wales) court name

FCL-656 | update high court naming to replace & with and

---

CHANGELOG.md
pyproject.toml

Release including the following:
- Allow court descriptions take contextual data
- Updates the court start_date data

Release v2.4.5

---

src/ds_caselaw_utils/courts.py
src/ds_caselaw_utils/test_courts.py

When a description had something that looks like a key to replace, it complained. This allows markdown to continue having things like `{target='blank'}` and we won't try to replace it.

FCL-709 | handle formatted markdown with {target='blank'} etc

---

CHANGELOG.md
pyproject.toml

Release including the following:
- Handle markdown with {target='blank'} when formatting

Release v2.4.6
