- src/ds_caselaw_utils/data/README.md
- src/ds_caselaw_utils/data/court_names.yaml
Whilst they aren't used in anger yet, worth saving the YAML data about court name mappings in an expected place.
> Add court names and documentation

- README.md
Adds shields which display the package's version and dependency status
> Add shields for package

- src/ds_caselaw_utils/data/court_names.yaml
Also ensure that Court of Protection and Family Court aren't flagged as being part of the high court.
> Ensure courts in alphabetical order in their parent courts

- src/ds_caselaw_utils/data/court_names.yaml
exactly what it says on the tin!
> move employment appeal tribunal to top of tribunals list

- CHANGELOG.md
- pyproject.toml
> version bump v1.2.1

- src/ds_caselaw_utils/data/court_names.yaml
The information appears to be entirely redundant.
> Remove second patent court

- src/ds_caselaw_utils/data/court_names.yaml
- src/ds_caselaw_utils/data/neutral_citation_regex.yaml
- src/ds_caselaw_utils/test_neutral.py
Not complete -- also requires changes in Public and Editor UI.
see also https://github.com/nationalarchives/ds-caselaw-public-ui/pull/1279, https://github.com/nationalarchives/ds-caselaw-editor-ui/pull/1494
> [FCL-134] Add IPT as a new court

- src/ds_caselaw_utils/data/court_names.yaml
- src/ds_caselaw_utils/data/neutral_citation_regex.yaml
https://national-archives.atlassian.net/browse/FCL-119
> Add crown and county courts (currently invisible)

- CHANGELOG.md
- pyproject.toml
Contains the stealth deploy of the Crown and County courts
> Release v1.5.4

- src/ds_caselaw_utils/data/court_names.yaml
https://national-archives.atlassian.net/browse/FCL-119
> County Court selectable and listable

- .github/workflows/publish.yml
- README.md
Identical code to https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/654 and https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/653
> Add write permissions for PyPI

- src/ds_caselaw_utils/data/court_names.yaml
https://national-archives.atlassian.net/browse/FCL-282
> Fix UKIPTrib start year

- src/ds_caselaw_utils/data/court_names.yaml
We wanted the Other Courts in alphabetical order.
https://dxw.slack.com/archives/C02TP2L2Z0F/p1725536045780679?thread_ts=1725533826.329839&cid=C02TP2L2Z0F
> Alphabetise other courts

- courts.md
- src/ds_caselaw_utils/data/court_names.yaml
These courts did _not_ end in the year given, and claiming they did is causing data errors elsewhere.
> [FCL-299] Remove incorrect end_year values for courts

- README.md
- courts.md
- scripts/build_courts_list
- src/ds_caselaw_utils/data/court_names.yaml
Now that we have judgments from the Crown Court, make it appear in lists and be selectable in search faceting.
Includes some bonus improvements to surface this visibility information in the courts list, and make the courts list visible in README.
> feat(FCL-323) make crown court selectable and listable

- CHANGELOG.md
- pyproject.toml
- **FCL-343**: Add typing to utils
> bump: version 1.6.0 → 1.7.0

- CHANGELOG.md
- pyproject.toml
- **Court**: add description data for all courts
- **Court**: add historical document data for all courts
> bump: version 2.1.0 → 2.2.0

- CHANGELOG.md
- pyproject.toml
- **Court**: updating court descriptions
> bump: version 2.2.0 → 2.2.1

- src/ds_caselaw_utils/courts.py
- src/ds_caselaw_utils/factory.py
- src/ds_caselaw_utils/test_courts.py
This allows downstream consumers to adjust their behaviour when displaying different types of body.
> feat(Court): add new `type` property to Court objects

- CHANGELOG.md
- pyproject.toml
- **Court**: add new `type` property to Court objects
> bump: version 2.2.1 → 2.3.0

- README.md
A tiny QoL change to add some more syntax highlighting to the README file.
> Add more syntax highlighting to README

- courts.md
- src/ds_caselaw_utils/data/court_names.yaml
https://national-archives.atlassian.net/browse/FCL-765
Open questions to confirm:
> Add UKIST trbiunal

- CHANGELOG.md
- pyproject.toml
- make params obligatory where courts are selectable or listable
> bump: version 2.4.0 → 2.4.1

- src/ds_caselaw_utils/data/court_names.yaml
- src/ds_caselaw_utils/data/neutral_citation_regex.yaml
https://editor.caselaw.nationalarchives.gov.uk/ewhc/mercantile/2014/1195 on the PUI didn't know how to parse the NCN
> Fix mercantile court

- courts.md
- scripts/build_courts_list
- src/ds_caselaw_utils/data/court_names.yaml
Only file that has been changed should be the courts yaml file,
> Added Consumer Credit Appeals Tribunal to yaml file

- README.md
Add requirements and setup instructions to README
> Add requirements and setup instructions to README

- courts.md
- src/ds_caselaw_utils/data/court_names.yaml
- src/ds_caselaw_utils/data/schema/courts.schema.json
- src/ds_caselaw_utils/types/courts_schema_autogen.py
Fixes the dates for estate agent tribunal
> FCL-903 | fix estate agent tribunal dates

- pyproject.toml
> [FCL-1050] Enable code complexity and security checks in ruff
